# Generated by Django 4.1.1 on 2024-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_insurance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.TextField(
                choices=[
                    ("Doctor", "Doctor"),
                    ("Nurse", "Nurse"),
                    ("Patient", "Patient"),
                ]
            ),
        ),
    ]
