# Generated by Django 4.1.1 on 2024-07-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="role",
            new_name="role_patient",
        ),
    ]
