# Generated by Django 4.1.1 on 2024-06-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalExamination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_complaints", models.TextField(blank=True, null=True)),
                ("objective_findings", models.TextField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("examination_date", models.DateField(auto_now_add=True)),
                ("prescription", models.TextField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "Doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_examinations_as_doctor",
                        to="users.user",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        limit_choices_to={"role": "Nurse"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_examinations_as_nurse",
                        to="users.user",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "Patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_examinations_as_patient",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
