# Generated by Django 4.1.1 on 2024-08-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_role_user_role_patient'),
        ('medical_examination', '0002_announcement_alter_medicalexamination_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexamination',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role_patient': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_examinations_as_doctor', to='users.user'),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='nurse',
            field=models.ForeignKey(limit_choices_to={'role_patient': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_examinations_as_nurse', to='users.user'),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role_patient': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_examinations_as_patient', to='users.user'),
        ),
    ]
