# Generated by Django 4.1.1 on 2024-08-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_calendar', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['day']},
        ),
    ]
