# Generated by Django 4.1.1 on 2024-08-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objednavkovy_kalendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("Vstupní vyšetření", "Vstupní vyšetření"),
                    ("Kontrola", "Kontrola"),
                    ("Recept", "Recept"),
                    ("Potvrzení, výpis", "Potvrzení, výpis"),
                    ("Jiný důvod", "Jiný důvod"),
                ],
                default="Doctor care",
                max_length=50,
            ),
        ),
    ]
