# Generated by Django 4.1.1 on 2024-08-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="biography",
        ),
    ]
