# Generated by Django 4.1.1 on 2024-08-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("surname", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("birth_date", models.DateField()),
                ("birth_number", models.CharField(blank=True, max_length=20)),
                (
                    "insurance",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Všeobecná zdravotní pojišťovna (111)"),
                            (2, "Vojenská zdravotní pojišťovna ČR (201)"),
                            (3, "Česká průmyslová zdravotní pojišťovna (205)"),
                            (4, "Oborová zdravotní poj. zam. bank, poj. a stav. (207)"),
                            (5, "Zdravotní pojišťovna ministerstva vnitra ČR (211)"),
                            (6, "Revírní bratrská pokladna, zdrav. pojišťovna (213)"),
                            (7, "Zaměstnanecká pojišťovna Škoda (209)"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("man", "muž"),
                            ("woman", "žena"),
                            ("non-binary", "nebinární"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "role_patient",
                    models.TextField(
                        choices=[
                            ("Doctor", "doktor"),
                            ("Nurse", "zdravotní sestra"),
                            ("Patient", "pacient"),
                        ]
                    ),
                ),
                ("address", models.TextField()),
                ("contact", models.TextField()),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["birth_date"],
            },
        ),
    ]
