# Generated by Django 4.1.1 on 2024-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_user_gender_alter_user_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insurance',
            field=models.IntegerField(),
        ),
    ]
