# Generated by Django 4.1.1 on 2024-08-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_user_gender_alter_user_role_patient'),
        ('patients', '0003_alter_user_insurance'),
    ]

    operations = [
    ]
