# Generated by Django 4.1.1 on 2024-08-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_user_insurance"),
        ("patients", "0003_merge_20240810_1126"),
    ]

    operations = []
