# Generated by Django 4.1.1 on 2024-08-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_merge_20240810_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insurance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Všeobecná zdravotní pojišťovna (111)'), (2, 'Vojenská zdravotní pojišťovna ČR (201)'), (3, 'Česká průmyslová zdravotní pojišťovna (205)'), (4, 'Oborová zdravotní poj. zam. bank, poj. a stav. (207)'), (5, 'Zdravotní pojišťovna ministerstva vnitra ČR (211)'), (6, 'Revírní bratrská pokladna, zdrav. pojišťovna (213)'), (7, 'Zaměstnanecká pojišťovna Škoda (209)')], default=1),
        ),
    ]
