# Generated by Django 4.1.1 on 2024-08-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_merge_20240810_1126'),
        ('patients', '0005_alter_user_insurance'),
    ]

    operations = [
    ]
