# Generated by Django 4.1.1 on 2024-08-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_merge_20240810_1413'),
        ('patients', '0006_merge_20240810_1503'),
    ]

    operations = [
    ]
