# Generated by Django 4.1.1 on 2024-08-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_merge_20240811_0912"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["surname", "name"]},
        ),
    ]
