# Generated by Django 4.1.1 on 2024-08-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="role_patient",
            field=models.TextField(
                choices=[
                    ("Patient", "pacient"),
                    ("Doctor", "doktor"),
                    ("Nurse", "zdravotní sestra"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=120),
        ),
    ]
